<?php

namespace Coach\CoachingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoachingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachingRepository extends EntityRepository
{
}
