<?php

namespace Coach\ConseilsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConseilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConseilRepository extends EntityRepository
{
}
