<?php

namespace Coach\PanneauBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PanneauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanneauRepository extends EntityRepository
{
}
