<?php

namespace Proxies\__CG__\Application\Sonata\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ContactPerson extends \Application\Sonata\UserBundle\Entity\ContactPerson implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'id', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'createdAt', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'updatedAt', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'nom', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'prenom', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'telephone', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'ville', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'cp', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'email', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'password_clear', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'adresse', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'profession', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'panneaux', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'estimation', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'reservations', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'commandes', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'annonces', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'messages_envoyes', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'messages_recus');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'id', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'createdAt', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'updatedAt', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'nom', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'prenom', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'telephone', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'ville', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'cp', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'email', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'password_clear', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'adresse', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'profession', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'panneaux', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'estimation', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'reservations', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'commandes', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'annonces', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'messages_envoyes', '' . "\0" . 'Application\\Sonata\\UserBundle\\Entity\\ContactPerson' . "\0" . 'messages_recus');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ContactPerson $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', array($ville));

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', array());

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setCp($cp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCp', array($cp));

        return parent::setCp($cp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCp', array());

        return parent::getCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array());

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', array());

        return parent::preUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function addPanneaux(\Coach\PanneauBundle\Entity\Panneau $panneaux)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPanneaux', array($panneaux));

        return parent::addPanneaux($panneaux);
    }

    /**
     * {@inheritDoc}
     */
    public function removePanneaux(\Coach\PanneauBundle\Entity\Panneau $panneaux)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePanneaux', array($panneaux));

        return parent::removePanneaux($panneaux);
    }

    /**
     * {@inheritDoc}
     */
    public function getPanneaux()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPanneaux', array());

        return parent::getPanneaux();
    }

    /**
     * {@inheritDoc}
     */
    public function addReservation(\Coach\ReservationBundle\Entity\Reservation $reservations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReservation', array($reservations));

        return parent::addReservation($reservations);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReservation(\Coach\ReservationBundle\Entity\Reservation $reservations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReservation', array($reservations));

        return parent::removeReservation($reservations);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservations', array());

        return parent::getReservations();
    }

    /**
     * {@inheritDoc}
     */
    public function addEstimation(\Coach\EstimationBundle\Entity\estimation $estimation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEstimation', array($estimation));

        return parent::addEstimation($estimation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEstimation(\Coach\EstimationBundle\Entity\estimation $estimation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEstimation', array($estimation));

        return parent::removeEstimation($estimation);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstimation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstimation', array());

        return parent::getEstimation();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfession($profession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfession', array($profession));

        return parent::setProfession($profession);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfession', array());

        return parent::getProfession();
    }

    /**
     * {@inheritDoc}
     */
    public function addAnnonce(\Coach\AnnonceBundle\Entity\Annonce $annonces)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAnnonce', array($annonces));

        return parent::addAnnonce($annonces);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAnnonce(\Coach\AnnonceBundle\Entity\Annonce $annonces)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAnnonce', array($annonces));

        return parent::removeAnnonce($annonces);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnonces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnonces', array());

        return parent::getAnnonces();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordClear($passwordClear)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordClear', array($passwordClear));

        return parent::setPasswordClear($passwordClear);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordClear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordClear', array());

        return parent::getPasswordClear();
    }

    /**
     * {@inheritDoc}
     */
    public function addMessagesEnvoye(\Application\Sonata\UserBundle\Entity\Message $messagesEnvoyes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMessagesEnvoye', array($messagesEnvoyes));

        return parent::addMessagesEnvoye($messagesEnvoyes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMessagesEnvoye(\Application\Sonata\UserBundle\Entity\Message $messagesEnvoyes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMessagesEnvoye', array($messagesEnvoyes));

        return parent::removeMessagesEnvoye($messagesEnvoyes);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessagesEnvoyes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessagesEnvoyes', array());

        return parent::getMessagesEnvoyes();
    }

    /**
     * {@inheritDoc}
     */
    public function addMessagesRecus(\Application\Sonata\UserBundle\Entity\Message $messagesRecus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMessagesRecus', array($messagesRecus));

        return parent::addMessagesRecus($messagesRecus);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMessagesRecus(\Application\Sonata\UserBundle\Entity\Message $messagesRecus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMessagesRecus', array($messagesRecus));

        return parent::removeMessagesRecus($messagesRecus);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessagesRecus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessagesRecus', array());

        return parent::getMessagesRecus();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommande(\Coach\AnnonceBundle\Entity\Commande $commandes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommande', array($commandes));

        return parent::addCommande($commandes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommande(\Coach\AnnonceBundle\Entity\Commande $commandes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommande', array($commandes));

        return parent::removeCommande($commandes);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommandes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommandes', array());

        return parent::getCommandes();
    }

}
