imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    #- { resource: stfalcon_tinymce.yml }
    #- { resource: ibrows_newsletter.yml }
framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8 
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"  
        types:
            json: Sonata\Doctrine\Types\JsonType
           
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                mappings:
                    ApplicationSonataUserBundle: 
                        type: annotation
                        prefix: Application\Sonata\UserBundle\Entity
                        dir: "%kernel.root_dir%/../src/Application/Sonata/UserBundle/Entity"
                        is_bundle: false
                    CoachAnnonceBundle: 
                        type: annotation
                        prefix: Coach\AnnonceBundle\Entity
                        dir: "%kernel.root_dir%/../src/Coach/AnnonceBundle/Entity"
                        is_bundle: false
                    ApplicationSonataNotificationBundle: 
                        type: annotation
                        prefix: Application\Sonata\NotificationBundle\Entity
                        dir: "%kernel.root_dir%/../src/Application/Sonata/NotificationBundle/Entity"
                        is_bundle: false    
                    SonataUserBundle: ~
                    FOSUserBundle: ~
                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~
                    SonataNotificationBundle: ~
                    CoachPageBundle: ~
                    CoachPackBundle: ~
                    CoachPanneauBundle: ~
                    CoachEstimationBundle: ~
                    CoachReservationBundle: ~
                    CoachConseilsBundle: ~
                    CoachCoachingBundle: ~
                    # ...

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager    
    service:
        user_manager: sonata.user.orm.user_manager 
    registration:
        form:
            type: coach_user_registration
sonata_user:
    security_acl: true
    manager_type: orm
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        sonata.media.block.media:
        sonata.media.block.gallery:
        sonata.media.block.feature_media:

sonata_admin:
    title:      Admin Panel
    title_logo: bundles/coachfront/images/ico/apple-touch-icon-57-precomposed.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
    dashboard:
        blocks:
            # display a dashboard block
        #- { position: left, type: sonata.admin.block.admin_list }
        # display two dashboard blocks
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Utilisateurs,Annonces,Packs,Commandes,Page Conseils Immo]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Mon Site,Reservations,Panneaux,Configuration,Messages]

        groups:
            Utilisateurs:
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    - application_sonata_user.admin.contact_person
            Reservations:
                items:
                    - coach_reservation.admin.reservation
            Annonces:
                items:
                    - coach_annonce_annonce.admin.user
                    - coach_annonce_type.admin.user
                    - coach_annonce_option.admin.user
                    - coach_annonce_class.admin.user
                    - coach_annonce_proximite.admin.user
            Packs:
                items:
                    - coach_pack_optioninfo.admin.user
                    - coach_pack_pack.admin.user
            Mon Site:
                items:
                    - coach_page.admin.page
                    - coach_page.admin.menu
                    - coach_page.admin.titre_page
                    - coach_coaching.admin.coaching
                    - coach_page.admin.block_social
                    - coach_page.admin.block_video
                    - coach_page.admin.block_text
                    - coach_page.admin.block_lienmiddle
            Panneaux:
                items:
                    - coach_panneau.admin.panneau
            Commandes:
                items:
                    - coach_annonce.admin.commande        
            Configuration:        
                items:
                    - coach_page.admin.email
                    - application_sonata_user.admin.contact 
            Page Conseils Immo:
                items:
                    - coach_conseils.admin.conseil
                
sonata_doctrine_orm_admin:
    # default value is null, so doctrine uses the value defined in the configuration
    entity_manager: ~
    templates:
        form:
            - SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig
        filter:
            - SonataDoctrineORMAdminBundle:Form:filter_admin_fields.html.twig
        types:
            list:
                array:      SonataAdminBundle:CRUD:list_array.html.twig
                boolean:    SonataAdminBundle:CRUD:list_boolean.html.twig
                date:       SonataAdminBundle:CRUD:list_date.html.twig
                time:       SonataAdminBundle:CRUD:list_time.html.twig
                datetime:   SonataAdminBundle:CRUD:list_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_list_field.html.twig
                trans:      SonataAdminBundle:CRUD:list_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_list_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_list_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_list_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_list_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_list_field.html.twig
                identifier: SonataAdminBundle:CRUD:base_list_field.html.twig
            show:
                array:      SonataAdminBundle:CRUD:show_array.html.twig
                boolean:    SonataAdminBundle:CRUD:show_boolean.html.twig
                date:       SonataAdminBundle:CRUD:show_date.html.twig
                time:       SonataAdminBundle:CRUD:show_time.html.twig
                datetime:   SonataAdminBundle:CRUD:show_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_show_field.html.twig
                trans:      SonataAdminBundle:CRUD:show_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_show_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_show_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_show_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_show_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_show_field.html.twig
# Configuration Sonata Cache
sonata_cache:
    caches:
        esi:
            token: an unique security key # a random one is generated by default
            servers:
                - varnishadm -T 127.0.0.1:2000 {{ COMMAND }} "{{ EXPRESSION }}"

        ssi:
            token: an unique security key # a random one is generated by default

# Configuration Sonata Block
sonata_block:
    default_contexts: [cms]
    context_manager: sonata.page.block.context_manager
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.page.block.children_pages:
        sonata.block.service.text:
        sonata.block.service.rss:
        sonata.formatter.block.formatter:

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

# Configuration Sonata Seo
sonata_seo:
    default:          sonata.seo.page.default
    encoding:         UTF-8
    page:
        title:            Particulier Coach
        metas:
            name:
                robots:               index, follow

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       Particulier & Coach
                'og:description':     particulier & coach

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

        head:
            #'xmlns':              http://www.w3.org/1999/xhtml
            #'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"

# Configuration KNP Menu
knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default
sonata_media:
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
#hype_mailchimp:
#    api_key: 350d4555194d03fd3f3d014383ff938f-us9
#    default_list: hamdi Company Newsletter
#    ssl: true      
gregwar_captcha: 
  reload:               true
  as_url:               true
  invalid_message:      Code Captcha incorrect          