coach_conseils:
    resource: "@CoachConseilsBundle/Resources/config/routing.yml"
    prefix:   /

coach_reservation:
    resource: "@CoachReservationBundle/Resources/config/routing.yml"
    prefix:   /
coach_coaching:
    resource: "@CoachCoachingBundle/Resources/config/routing.yml"
    prefix:   /
coach_panneau:
    resource: "@CoachPanneauBundle/Resources/config/routing.yml"
    prefix:   /
coach_estimation:
    resource: "@CoachEstimationBundle/Resources/config/routing.yml"
    prefix:   /
coach_page:
    resource: "@CoachPageBundle/Resources/config/routing.yml"
    prefix:   /
coach_newsletter:
    resource: "@CoachNewsletterBundle/Resources/config/routing.yml"
    prefix:   /
coach_user_sonata:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/routing.yml"
    prefix:   /
coach_front:
    resource: "@CoachFrontBundle/Resources/config/routing.yml"
    prefix:   /
coach_annonce:
    resource: "@CoachAnnonceBundle/Resources/config/routing.yml"
    prefix:   /
coach_pack:
    resource: "@CoachPackBundle/Resources/config/routing.yml"
    prefix:   /
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin    
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"
sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting
sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile
sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register
sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery
media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb