<?php

namespace Coach\AnnonceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClassAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassAnnonceRepository extends EntityRepository
{
}
