<?php

namespace Coach\AnnonceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OptionAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionAnnonceRepository extends EntityRepository
{
}
