<?php

namespace Coach\AnnonceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * villeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class villeRepository extends EntityRepository
{
    public function findVillesLike( $term, $limit = 10 )
    {
 
	$qb = $this->createQueryBuilder('c');
	$qb ->select('c.name, c.code_postal')
	->where('c.name LIKE :term')
	->setParameter('term', $term.'%')
        ->orderBy("c.name", 'DESC')        
	->setMaxResults($limit);
 
	$arrayAss= $qb->getQuery()
	->getArrayResult();
        
	// Transformer le tableau associatif en un tableau standard
        $array = array();
        foreach ($arrayAss as $row) {
                $array[] = array("CodePostal"=>$row['code_postal'], "Ville"=>$row['name']);
        }
	return $array;
}	
 
public function findCodesPostauxLike( $term, $limit = 10 )
{ 
	$qb = $this->createQueryBuilder('c');
	$qb ->select('c.name, c.code_postal')
	->where('c.code_postal LIKE :term')
	->setParameter('term', $term.'%')
        ->orderBy("c.name", 'DESC')        
	->setMaxResults($limit);
 
	$arrayAss= $qb->getQuery()
	->getArrayResult();
 
	
	// Transformer le tableau associatif en un tableau standard
        $array = array();
        foreach ($arrayAss as $row) {
                $array[] = array("CodePostal"=>$row['code_postal'], "Ville"=>$row['name']);
        }
 
	return $array;
}
}
