<?php

namespace Coach\AnnonceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{
    public function cleanup($days)
    {
        $query = $this->createQueryBuilder('j')
        ->delete()
        ->where('j.is_activated IS NULL')
        ->andWhere('j.created_at < :created_at') ->setParameter('created_at', date('Y-m-d', time() - 86400 * $days))
        ->getQuery();
        return $query->execute();
    }
}
