<?php

namespace Coach\AnnonceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAnnonceRepository extends EntityRepository
{
}
