<?php

namespace Coach\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TitrePageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitrePageRepository extends EntityRepository
{
}
